config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, :controllers => {
    :sessions => 'users/sessions',
    :registrations => 'users/registrations',
  }
  resources :events do
    resources :comments, only: [:create]
    resources :attendances, only: [:create, :destroy]
  end
  resources :users, only: [:show]
  root 'root_pages#index'
  get 'root_pages/show'
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :attendances, dependent: :destroy
  has_many :participants, through: :attendances, source: :user
  mount_uploader :image, ImageUploader
  with_options presence: true do
    validates :title
    validates :user_id
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :user_signed_in?, only: [:update, :create]
  before_action :correct_user, only: [:destroy]
  def show
    @event = Event.find(params[:id])
    @comments = @event.comments.paginate(page: params[:page])
    @comment = Comment.new
    @attendance = Attendance.new
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(event_params)
    @event.start_time.to_time
    if @event.save
      flash[:success] = "イベントが作成されました！"
      @event.attendances.create(user_id: current_user.id)
      redirect_to user_path(current_user)
    else
      render 'new'
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update_attributes(event_params)
      flash[:success] = "イベントがアップデートされました"
      redirect_to @event
    else
      render 'edit'
    end
  end

  def destroy
    @event.destroy
    flash[:success] = "イベントが削除されました"
    redirect_to user_path(current_user.id)
  end

  private

  # ストロングパラメーター
  def event_params
    params.require(:event).permit(:title, :details, :start_time, :place, :image)
  end

  def correct_user
    @event = current_user.events.find_by(id: params[:id])
    redirect_to user_path(current_user.id) if @event.nil?
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_comments.html.erb
<div class="col-md-9 col-sm-8 col-xs-12 comments_list">
  <% if event.comments.any? %>
    <h3>Comments (<%= event.comments.count %>)</h3>
    <ol class="comment">
      <%= render comments%>
    </ol>
    <%= will_paginate comments %>
  <% end %>
  <%= form_for [event, comment] do |f| %>
  <%= p event.id %>
    <%= f.text_field :content %>
    <%= f.hidden_field :event_id, value: event.id %>
    <br>
    <%= f.submit 'コメントする' %>
  <% end %>
</div>

app/views/events/_event.html.erb
<li id="event-<%= event.id %>">
  <span class="event_title"><%= link_to event.title, event_path(event.id) %></span>
  <span class="user"><%= link_to event.user.username, event.user %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(event.created_at) %> ago.
  </span>
</li>

app/views/events/_participants.html.erb
<div class="col-md-3 col-sm-4 col-xs-12 participants_list">
  <h2>参加者(<%= event.attendances.count %>)</h2>
  <% event.participants.each do |user| %>
    <li><%= user.username %></li>
    <hr>
  <% end %>
</div>

app/views/events/edit.html.erb
<h1>イベント編集</h1>

<%= form_for(@event)  do |f| %>
  <div class="form-group">
    <label for="eventFormTextField1">イベントタイトル</label>
    <%= f.text_field :title, class: "form-control",autocomplete: "title" %>
  </div>
  <div class="form-group">
    <label for="exampleFormControlTextarea２">イベント詳細</label>
    <%= f.text_area :details, class: "form-control", autocomplete: "details", rows: "3"%>
  </div>
  <div class="form-group">
    <label for="eventFormTextField2">集合場所</label>
    <%= f.text_field :place, class: "form-control",autocomplete: "place"%>
  </div>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="form-group">
    <label for="eventFormTextField3">イベント開催時間</label>
    <%= f.text_field :start_time, class: "form-control datetimepicker-input", id: "start_time", data: {toggle: "datetimepicker", target: "#start_time"} %>
  </div>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/events/new.html.erb
<h1>イベント作成</h1>

<%= form_with model: @event do |f| %>
  <div class="form-group">
    <label for="eventFormTextField1">イベントタイトル</label>
    <%= f.text_field :title, class: "form-control"%>
  </div>
  <div class="form-group">
    <label for="exampleFormControlTextarea２">イベント詳細</label>
    <%= f.text_area :details, class: "form-control",rows: "3"%>
  </div>
  <div class="form-group">
    <label for="eventFormTextField2">集合場所</label>
    <%= f.text_field :place, class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="row">
      <div class="col-sm-6">
          <div class="form-group">
              <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
                  <%= f.text_field :start_time, class: "form-control datetimepicker-input", id: "start_time", data: {toggle: "datetimepicker", target: "#start_time"} %>
                  <div class="input-group-append" data-target="#start_time" data-toggle="datetimepicker">
                      <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                  </div>
              </div>
          </div>
      </div>
      <script type="text/javascript">
          $(function () {
              $('#datetimepicker1').datetimepicker();
          });
      </script>
  </div>
  <%= f.submit "イベントを作成する", class: "btn btn-primary" %>
<% end %>

app/views/events/show.html.erb
<% if current_user == @event.user %>
  <button type="button" class="btn btn-primary">
    <%= link_to "イベントを編集する", edit_event_path(@event) %>
  </button>
<% end %>
<h2><%= @event.title %></h2>
<% if @event.image.presence %>
  <p>
    <strong>Picture</strong>
    <%= image_tag @event.image_url ,class: "img-fluid", alt: "image"%>
  </p>
<% end %>
<p><%= @event.details %></p>
<p><%= @event.place %></p>
<p><%= @event.start_time %></p>
<p><%= @event.user.username %></p>
<% unless @event.user_id == current_user.id then %>
  <% if current_user.already_attended?(@event) %>
    <button type="button" class="btn btn-secondary">
      <%= link_to "イベント参加を取り消す", event_attendance_path(params[:id]), method: :delete %>
    </button>
  <% else %>
    <button type="button" class="btn btn-primary">
      <%= link_to "イベントに参加する", event_attendances_path(params[:id]), method: :create %>
    </button>
  <% end %>
<% end %>

<% if current_user == @event.user %>
  <%= link_to "delete", @event, method: :delete,
                                   data: { confirm: "You sure?" } %>
<% end %>
<div class="row">
  <%= render "comments", event: @event,comments: @comments, comment: @comment %>
  <%= render "participants", event: @event %>
</div>