config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, :controllers => {
    :sessions => 'users/sessions',
    :registrations => 'users/registrations',
  }
  resources :events do
    resources :comments, only: [:create]
    resources :attendances, only: [:create, :destroy]
  end
  resources :users, only: [:show]
  root 'root_pages#index'
  get 'root_pages/show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :event
  belongs_to :user
  validates_uniqueness_of :event_id, scope: :user_id
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :attendances, dependent: :destroy
  has_many :participants, through: :attendances, source: :user
  mount_uploader :image, ImageUploader
  with_options presence: true do
    validates :title
    validates :user_id
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events, dependent: :destroy
  has_many :comments
  has_many :attendances, dependent: :destroy
  has_many :participants, through: :attendances, source: :user
  mount_uploader :image, ImageUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:twitter]

  def already_attended?(event)
    attendances.exists?(event_id: event.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  def create
    @attendance = current_user.attendances.create(event_id: params[:event_id])
    redirect_back(fallback_location: event_path(params[:event_id]))
  end

  def destroy
    @attendance = Attendance.find_by(event_id: params[:event_id])
    @attendance.destroy
    redirect_back(fallback_location: event_path(params[:event_id]))
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = current_user.comments.new(comment_params)
    if @comment.save
      flash[:success] = "コメントしました"
      redirect_back(fallback_location: root_path)
    else
      flash[:danger] = "コメントできません"
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :event_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :user_signed_in?, only: [:update, :create]
  before_action :correct_user, only: [:destroy]
  def show
    @event = Event.find(params[:id])
    @comments = @event.comments.paginate(page: params[:page])
    @comment = Comment.new
    @attendance = Attendance.new
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(event_params)
    @event.start_time.to_time
    if @event.save
      flash[:success] = "イベントが作成されました！"
      @event.attendances.create(user_id: current_user.id)
      redirect_to user_path(current_user)
    else
      render 'new'
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update_attributes(event_params)
      flash[:success] = "イベントがアップデートされました"
      redirect_to @event
    else
      render 'edit'
    end
  end

  def destroy
    @event.destroy
    flash[:success] = "イベントが削除されました"
    redirect_to user_path(current_user.id)
  end

  private

  # ストロングパラメーター
  def event_params
    params.require(:event).permit(:title, :details, :start_time, :place, :image)
  end

  def correct_user
    @event = current_user.events.find_by(id: params[:id])
    redirect_to user_path(current_user.id) if @event.nil?
  end
end

app/controllers/root_pages_controller.rb
class RootPagesController < ApplicationController
  def index
    @events = Event.where('start_time >= ?', Time.now).paginate(page: params[:page])
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
  end

  # POST /resource/sign_in
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_signed_in?, only: [:update]

  def show
    @user = User.find_by(id: params[:id])
    @events = @user.events.order(created_at: :desc).paginate(page: params[:page])
  end

  private

  # ストロングパラメーター
  def user_params
    params.require(:user).permit(:username, :email, :password,
                                 :password_confirmation, :introduce, :image)
  end

  # ログイン済みユーザーかどうか確認
  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/root_pages_helper.rb
module RootPagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
  end

  # 現在ログイン中のユーザーを返す (いる場合)
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  # ユーザーがログインしていればtrue、その他ならfalseを返す
  def user_signed_in?
    !current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  # 引数で与えられたユーザーのGravatar画像を返す
  def gravatar_for(user)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.username, class: "gravatar")
  end
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <nav class="navbar fixed-bottom navbar-light bg-light">
      <small>
        To the better world with your Moto.
        by <%= link_to "Hase",   '#' %>
      </small>
      <ul>
        <li><%= link_to "About",   '#' %></li>
        <li><%= link_to "Contact", '#' %></li>
        <li><a href="http://news.railstutorial.org/">News</a></li>
      </ul>
    </nav>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="container">
    <nav class="navbar navbar-expand-lg fixed-top navbar-light bg-light">
      <div class="HeaderLogo">
        <h1><%= link_to 'Circle of Bike', root_path %></h1>
      </div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <% if user_signed_in? %>
              <li class="nav-link">
                <%= gravatar_for current_user %>
                <strong><%= link_to current_user.username, user_path(current_user.id) %></strong>
              </li>
              <li class="nav-link"><%= link_to 'プロフィール変更', edit_user_registration_path(current_user.id) %></li>
              <li class="nav-link"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
          <% else %>
              <li class="nav-link"><%= link_to 'サインアップ', new_user_registration_path %></li>
              <li class="nav-link"><%= link_to 'ログイン', new_user_session_path %></li>
          <% end %>
          <li class="nav-link">
            <%= link_to 'イベントを作成する', new_event_path %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bike site</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
      <%= render 'layouts/header' %>
  <body>

    <main>
      <div class="container">
        <%= render 'layouts/flash_messages' %>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <%= yield %>
        <%= render 'layouts/footer' %>
      </div>
    </main>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>